language: python
python:
  - "2.7.10"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pip install nose coverage codecov
  - nosetests -v --with-coverage
after_success:
  - codecov
