---
- hosts: tabi
  tasks:
  - name: Creating Tabi Directory
    file:
      path: "{{ ansible_user_dir }}/tabi"
      state: directory
    tags: dir

  - name: supervisor_stop
    supervisorctl:
      name: tabi
      state: stopped
    become: true
    ignore_errors: yes
    tags: stop

  - name: Copying Build Artifacts
    synchronize:
      src: "{{ tabi_src }}"
      dest: "{{ ansible_user_dir }}/tabi"

  - name: copy config file
    template:
      src: "templates/tabi-conf.j2"
      dest: "/etc/supervisor/conf.d/tabi.conf"
    become: true

  - name: Build Tabi
    shell: python setup.py install
    args:
      chdir: "{{ ansible_user_dir }}/tabi"
    become: true
    tags: build

  - name: supervisorctl reread
    supervisorctl:
      name: tabi
      state: present
    become: true
    tags: reread

  - name: supervisor start
    supervisorctl:
      name: tabi
      state: started
    become: true
    tags: start
