---
- hosts: tabi
  become: true
  become_user: root
  tasks:
  - name: Creating Tabi Directory
    file:
      path: '{{ tabi_dest_loc }}'
      state: directory
    tags: dir

  - name: supervisor_stop
    supervisorctl:
      name: tabi
      state: stopped
    tags: stop

  - name: Modifying Supervisor Directory Location
    ini_file: dest=/etc/supervisor/conf.d/tabi.conf section="program:tabi" option=directory value='{{tabi_dest_loc}}' backup=yes
    tags: configuration

  - name: Copying Build Artifacts
    synchronize:
      src: '{{ tabi_src_loc }}'
      dest: '{{ tabi_dest_loc }}'

  - name: Build Tabi
    shell: python setup.py install
    args:
      chdir: /home/pramati/tabi
    become: true
    tags: build

  - name: supervisor_start
    supervisorctl:
      name: tabi
      state: started
    tags: start
